{% set name = "skmatter" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 699993a4bae1caa8eb8a7d1ce5adb9b0eee4fbdf1ccb279c5831c734ac454f0c

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - scikit-learn >=1.7,<1.8
    - scipy >=1.15

test:
  imports:
    - skmatter
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/lab-cosmo/scikit-matter
  summary: 'A collection of scikit-learn compatible utilities that implement methods born out of the materials science and chemistry communities'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://scikit-matter.readthedocs.io

extra:
  recipe-maintainers:
    - PicoCentauri
    - Luthaf
